server:
  port: 8123
  servlet:
    context-path: /api

spring:
  # 指定 lcoal yml 环境
  profiles:
    active: local

  application:
    name: chunchun-pic-backend
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/chun_cloud_picture
    username: chunchun
    password: chunchun

mybatis-plus:
  configuration:
    # MyBatis 配置
    map-underscore-to-camel-case: false
    # log 配置 # 仅在开发环境
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      # 逻辑删除 不是物理删除
      logic-delete-field: isDelete
      logic-delete-value: 1
      logic-not-delete-value: 0
# 接口文档配置
knife4j:
  enable: true
  openapi:
    title: 接口文档
    version: v1.0
    group:
      default:
        api-rule: package
        api-rule-resources:
          - com.chunchun.chunpicturebackend.controller

## 对象存储配置（需要从腾讯云获取）
#cos:
#  client:
#    host: xxx
#    secretId:
#    secretKey:
#    region: xxx
#    bucket: xxx
